spring:
  application:
    name: friendsMatching
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: userCenter
    password: 1111
    url: jdbc:mysql://localhost/userCenter?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false